### ISSUE TITLE
Support indexing of hOCR

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/content_search#167]
This is a request to adds support for hOCR, the format used by Google Books. See sul-dlss/exhibits#1357. 

Assumptions:

* hOCR files will have `role="transcription"` associated with them in their contentMetadata for their objects, as ALTO and page-level plain text have.

**Comment by andrewjbtw** [comment]
Hi @anarchivist, with the Google Books infrastructure work cycle coming up, I wanted to check on the status of this. We are considering converting hOCR to ALTO as part of the conversion between what Google provides and what will be ingested into SDR, but it doesn't sound like that would be necessary if content_search can support hOCR.

**Comment by caaster** [comment]
content_search does not support hOCR -- I'm 99% positive, @andrewjbtw. I can check in with the Access team and get back to you since Mark is out of the office this week.

**Comment by anarchivist** [comment]
It doesn't support hOCR yet (neither does Exhibits, hence the ticket above). Do we know the expected volume/rate of accessioning we're trying to achieve for Google Books?

**Comment by caaster** [comment]
@cbeer just weighed in with this important note: "It wouldn’t be a problem to support it though, it just hasn’t been a priority. We certainly shouldn’t convert hOCR to Alto just because content search only does Alto (and plain text) right now, though."

**Comment by andrewjbtw** [comment]
Ok, I'll let the team know we likely shouldn't spend time on conversion.

I don't think the scope of the Google Books work cycle has been fully defined yet. It is not clear to me if we are going to begin accessioning at a high volume by the end of the work cycle or if the goal is to get the underlying infrastructure in place to start that accessioning at a later date. The conversion question came up because it's something that would be more of a challenge to do after the books are accessioned.

**Comment by hannahfrost** [comment]
I think it would be useful to know the level of effort to enable support of hOCR in our current environment, @cbeer . Is that knowable?

**Comment by cbeer** [comment]
Minimal. We build contentsearch with other format types in mind. I think the bigger level of effort will be scaling content search up to support all this new content.

**Comment by caaster** [comment]
@andrewjbtw I wanted to make sure you & the team are aware of this constraint: Note that items requiring authorization to view or download (such as world no download, Stanford only or Stanford no download, or citation only) cannot currently take advantage of full text or content search. -- this is documented here: https://consul.stanford.edu/display/DLSSDOCS/Making+sure+your+textual+objects+can+be+searched. Friendly reminder of the full text search demo exhibit: https://exhibits.stanford.edu/jarndyce-test
