### ISSUE TITLE
Should we restrict indexing OCR files to reasonable resources?

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/content_search#28]
We currently are indexing file object based on mimetype.  Should we also restrict those to files that are within resources that we would reasonably expect xml/text to represent OCR (e.g. `page`)?

Examples:
- Does not contain OCR: https://purl.stanford.edu/dw626qp2349
- Does contain OCR: https://purl.stanford.edu/cc842mn9348

Another question this raises is should we also omit OCR when it is at the object level and not at the resource level (e.g. https://purl.stanford.edu/zy575vf8599).  If we can't reference a canvas that the hit is on, then we obviously cannot return a useful annotation reference (other than 0,0,0,0 on the first canvas for all hits, which seems sub-optimal).

**Comment by cbeer** [comment]
We're only advertising support in PURL for `page` resources (https://github.com/sul-dlss/purl/pull/198/files#diff-646ad6b10917e4385cbcc8c8524e24a2R9).

**Comment by anarchivist** [comment]
Superseded by #47
