### ISSUE TITLE
Add support for ALTO3

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/content_search#3]

**Comment by cbeer** [comment]
Here is the ALTO2 example:

https://github.com/sul-dlss/content_search/blob/master/lib/alto_payload_delimited_transformer.rb

I wonder if it's enough to just detect whether the content is ALTO2/3 and adjust the namespace as appropriate.

**Comment by anarchivist** [comment]
See also https://github.com/altoxml/documentation/wiki/v3.0-Changes
