### ISSUE TITLE
Content search misses some matches

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/content_search#30]
This might not be news to anyone (maybe just a limitation of the OCR?) but just in case I want to note a discrepancy in the search results I found when searching a VT document using the viewer versus search the document PDF directly. 

For the viewer mockup I'm working on, I used `cc842mn9348` as an example item. Below is a comparison of the search results I get when searching "trial":

```
Page  PDF hits  Viewer hits
----  --------  -----------
 2       3           2
 4       1           0
 6       4           3
 7       6           4
 8       6           4
 9       4           4
18       1           1
```

So for a couple of pages the viewer search gets them all, but in several other pages the viewer search misses one or two occurrences. For example, the viewer search missed the occurrence of "trial" on page 4, which is clearly there near the end of paragraph 13.

This is the only document and search term where I've done this comparison, but presumably the pattern would hold for other terms and documents (unless I got really lucky with the one document I tried!).

Is this a known or expected limitation of the OCR?

**Comment by jkeck** [comment]
@ggeisler at a quick glance, this appears to be an issue with how we've configured solr to analyze the incoming user query.

Just using the 1st example (page 2), our OCR contains 3 instances of "trial".  Looking at the solr document that is returned, the field that we index the OCR content into contains 3 instances of "trial".  However; once we query for "trial" we're only returned two annotations.

I have a feeling this has to do with how we're analyzing the incoming query.  Making queries directly against solr I'm able to reproduce the same thing, but notice that if I provide a comma in my query, I get the other instance of "trial" (which I noticed includes the `,` in the OCR).

See ["trial"](https://solr.example.com/solr/contentsearch-uat/select?fq=druid:cc842mn9348&fq=id:cc842mn9348/cc842mn9348_3/EastTimor_CE-SPSC_Final_Decisions_2001_04b-2001_Sabino_Gouveia_Leite_Judgment_0002.xml&hl.fl=ocrtext&hl=true&hl.snippets=10&hl.method=fastVector&wt=json&q=trial) vs ["trial,"](https://solr.example.com/solr/contentsearch-uat/select?fq=druid:cc842mn9348&fq=id:cc842mn9348/cc842mn9348_3/EastTimor_CE-SPSC_Final_Decisions_2001_04b-2001_Sabino_Gouveia_Leite_Judgment_0002.xml&hl.fl=ocrtext&hl=true&hl.snippets=10&hl.method=fastVector&wt=json&q=trial,). (Note: change the host to our solr instance).

I think this should be relatively straight forward to deal with, but not 100% sure if there are other implications we need to consider.

**Comment by ggeisler** [comment]
@jkeck I see, thanks. Yeah, I'm not sure I know all of the potential implications we should consider, but it does seem (I think you are also assuming this) that we'd want to find matches where punctuation is excluded (e.g., a search for "trial" should match "trial," or "trial."). That would be a common and reasonable user expectation, I believe.

**Comment by jkeck** [comment]
Agreed.

**Comment by cbeer** [comment]
The punctuation problem should be fixed by https://github.com/sul-dlss/content_search/pull/22 and just needs to be deployed + reindexed.

**Comment by ggeisler** [comment]
Okay, great.

**Comment by cbeer** [comment]
Deployed; now the content just needs to be reindexed.
