### ISSUE TITLE
Certain objects not returning results past the first or second page

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/content_search#300]
Reported by @dinahhandel and @andrewjbtw: the content search endpoint for https://purl.stanford.edu/th858cc1348 is only returning results from the first page (and occasionally the second page) of text for the object. 

Per Andrew, the word “gentle” is on more than one page (based on grepping the ALTO files on the file system) but only the first page result is returned.

**Comment by cbeer** [comment]
@mejackreed and I took a look into this.

The third page of this object has an `alto:TextLine` with ~1500+ words in it, which is breaking some fundamental limitations in our Solr schema that drives the autocomplete widget. The good news is we intend to drop autocomplete which should fix this without any additional work (and hopefully there are no other issues 🤷 ).

That said, the OCR there (iirc... around the 49th TextLine) is a little suspect for being at least an order of magnitude bigger than expected 🤷‍♂️.

**Comment by anarchivist** [comment]
ref sul-dlss/purl#467

**Comment by cbeer** [comment]
Fixed  by #302
