### ISSUE TITLE
Content search UI recommendations

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/content_search#33]
Below are mockups to suggest, at least for discussion, UI updates needed to provide a better user experience when searching content from within a viewer (starting from the current UV).

## Recommendations
We have a number of recommendations for updating the viewer UI that go beyond the mockups below (JV has a 10-page PDF with them); the mockups below focus only on recommendations for 1) updating the UI elements related to showing search results in the viewer and 2) changing viewer behavior in response to the user using the search UI elements (or zooming while viewing search results).

### Updates to existing UV UI elements
 - Eliminate the two rows that contain the teardrop icons and the previous/next result information.
 - Eliminate the blue-bordered highlight that surrounds the thumbnail area when a document is selected (to be replaced with a more prominent document highlight). sul-dlss/uv-en-GB-theme#2  sul-dlss/uv-en-GB-theme#4
 - Eliminate the white-bordered styling on the currently selected thumbnail (covered by the more prominent document highlight mentioned above). sul-dlss/uv-en-GB-theme#2
 - Update the sidebar scrollbar to more closely resemble a browser scrollbar.
 - Add small arrow icons next to the sidebar scrollbar to indicate which pages have search result hits (similar in function to the current teardrop icons).
 - Add a search box to the bottom of the sidebar.
 - Add hit count indicator and hit navigation adjacent to the search box.

### Updates to viewer behavior
- If a user arrives at the item show page by selecting the item from a search result page, the viewer should load with the search term used in executing the search (i.e., the results page hands off the search term to the viewer); the search box in the Contents sidebar is populated with the term and the hit highlighting is shown as in the mockups below. If the user didn't include any search terms, or arrived at the show page via other means, the viewer loads with the search box empty. This is similar to the approach used by the National Library of Wales for their [journal search]( https://journals.library.wales/search?query=green&range%5Bmin%5D=1735&range%5Bmax%5D=2007&lang%5B%5D=en) (though they show results at the page, rather than document level, so not sure if that affects feasibility)
- When a search is performed in the viewer (or pre-populated as described above), the results are shown as in the mockup below:

<img width="568" alt="page-8-100 -hit-17" src="https://user-images.githubusercontent.com/101482/34731868-d134d64c-f520-11e7-9d6f-6fefa0ad2040.png">

- Arrow icons next to the scrollbar show which pages in the document have hits. In this example (Druid cc842mn9348), there are hits on pages 2, 4, 6, 7, 8, 9, 18, and 46 (the last is not a real hit in that document, but included to show how things look when the last page in the document has a hit). The first page in the document with a hit is selected and indicated by the colored arrow icon and the rectangular border.

- The document is initially shown at 100% zoom-level, not zoomed in on the hit as the viewer currently does. sul-dlss/universalviewer#46

- The hit indicator shows the currently active hit with the total number of matches (1/25). The previous and next icons enable the user to move through the matches.

- The currently active hit is highlighted with a different color than the other matches on the page. (We might have to work on exact colors to ensure accessible contrast.)

- As the user navigates through the matches with the prev/next icons, the highlight color of the matches change accordingly.

- sul-dlss/universalviewer#46 The zoom level stays at the current zoom level as the user navigates through matches using the prev/next icons. If the user changes the zoom level to, say, 150% at some point, the zoom level stays at 150% as the user uses the prev/next icons. This is the case even if navigating the matches takes the user to a new page in the document (this is so the user's focus on matches is not disturbed by a change in zoom level when moving to a new page). So, for example, if the user had zoomed in on page 8 and was using the next icon to move through the hits in the mockup until reaching the last one on the page (hit 20):

<img width="569" alt="page-8-zoomed-hit-20" src="https://user-images.githubusercontent.com/101482/34732217-d36266e0-f521-11e7-9678-d41a1fb32055.png">

when next clicking the next icon they'd see the page change to this for the next match (hit 21):

<img width="569" alt="page-9 zoomed-hit-21" src="https://user-images.githubusercontent.com/101482/34732251-f466264c-f521-11e7-81bd-c41c20d13945.png">

- sul-dlss/universalviewer#46 If, however, the user navigates to another page in the document, either by clicking a page thumbnail or by clicking one of the arrow icons, the newly displayed page is shown at 100%, even if the user was currently viewing at at a zoom level other than 100%. (This is so the user can see the complete context of hits when jumping to a new page, since they have already lost some focus on the hits by manually changing pages by means other than the prev/next icons.) So even if the user was zoomed in on page 8, if the user then clicked page 9 in the sidebar or clicked the page 9 hit indicator arrow, they'd see page 9 like this:

<img width="571" alt="page-9-100 -hit-21" src="https://user-images.githubusercontent.com/101482/34732324-33b3845c-f522-11e7-825d-8a95a3a7c011.png">

- If the user clears the search terms, or arrives at the item show page that hasn't been handed any search terms, the search box is empty but should show a search icon to make clear the purpose of the control. Ideally, the search icon is just implemented like placeholder text; it is visible when the search box is empty, but as soon as the user clicks in the box or the box contains search terms, the search icon is not visible (this saves on horizontal space, which is tight in this design).

<img width="197" alt="empty-search-box" src="https://user-images.githubusercontent.com/101482/34732009-32b1de4c-f521-11e7-8c29-8cddb6c4e555.png">

- If the user hovers over a page indicator when results are displayed, a tooltip displays the page number and number of hits on that page. Ideally, if the page is not the currently displayed page, the hit indicator text is linked so the user can click directly in the tooltip to move to that page in the viewer.

<img width="173" alt="page-indicator-tooltip" src="https://user-images.githubusercontent.com/101482/34732004-2b228eb0-f521-11e7-9b49-1a1284ec9c95.png">

**Comment by cbeer** [comment]
UV doesn't seem to request autocomplete suggestions for multi-term queries?

![2018-01-19 07_57_31](https://user-images.githubusercontent.com/111218/35159274-7fe32d2c-fcee-11e7-98a6-95221f36feef.gif)

**Comment by anarchivist** [comment]
ref UniversalViewer/universalviewer#529 and UniversalViewer/user-stories#9

**Comment by ggeisler** [comment]
This ticket involved several features that we decided might be better approached as individual tickets, in the UniversalViewer/universalviewer repo. So I'm closing this ticket in favor of these tickets:

- #[545](https://github.com/UniversalViewer/universalviewer/issues/545) - Desired zoom behavior for content search, with current UV UI
- #[546](https://github.com/UniversalViewer/universalviewer/issues/546) - Explore more optimal approach to zoom level of first matched page
- #[547](https://github.com/UniversalViewer/universalviewer/issues/547) - Update highlighting style for current match versus other matches in content search
- #[548](https://github.com/UniversalViewer/universalviewer/issues/548) - Update UI elements involved in content search
- #[550](https://github.com/UniversalViewer/universalviewer/issues/550) - Passing query terms to UV
