### ISSUE TITLE
Content search not working for druid:hn876tb4569

### ISSUE THREAD

**Issue by caaster** [sul-dlss/content_search#350]
Content search is not working for the following: druid:hn876tb4569, as reported by the Hoover Institution today.

@anarchivist pointed out, after preliminary analysis, that the problem appears to be caused by the recent decoupling work of SDR from Fedora 3. It seems that the correct canvas/resource IDs were not created (related to Infra team changes to cocina). A fix for this needs to be figured out, and likely a mass reindexing of content search-enabled resources in the SDR.

<details><summary>This is a priority to resolve, not just for Hoover, but because of a new digital collections project that commenced in October with Stanford Faculty collaboration, as described below:</summary>
In October, the Digital Production Group began a project to digitize a selection of materials from the Suzanne Comhaire-Sylvain papers. Comhaire-Sylvain was the first woman Haitian anthropologist, and conducted anthropological work around the world. She was part of a family of groundbreaking women: her sister, Yvonne Sylvain, was the first Haitian woman physician and the first gynecologist-obstetrician of the country, and her other sister, Madeleine Sylvain, was one of the founders of the "Ligue Feminine d’Action Sociale" (Feminine League for Social Action) which fought for women's legal rights. Suzanne Comhaire-Sylvain's anthropological work focused on women in Haiti and Africa, Haitian folklore, and Creole. The items to be digitized include: the rare newspaper "La Voix des Femmes" (Women's voices), which published many articles by Comhaire-Sylvain; field notes; family correspondence; photographs; and other materials. The project will also support an upcoming special journal issue led by Stanford faculty member Dr. Fatoumata Seck. The project was proposed by Regina Roberts and Sarah Sussman.
</details> 

P.S. These appear to be red herrings: the problem has nothing to do with the French OCR, nor with ABBYY 3.1 compatibility with content search.

**Comment by anarchivist** [comment]
For example, looking at  https://contentsearch.stanford.edu/hn876tb4569/search?q=revanche :

```json
{
  "@context": [
    "http://iiif.io/api/presentation/2/context.json",
    "http://iiif.io/api/search/1/context.json"
  ],
  "@id": "https://contentsearch.stanford.edu/hn876tb4569/search?q=revanche",
  "@type": "sc:AnnotationList",
  "resources": [
    {
      "@id": "https://purl.stanford.edu/hn876tb4569/iiif/canvas/http:/text/at/4442,378,1188,112",
      "@type": "oa:Annotation",
      "motivation": "sc:painting",
      "resource": {
        "@type": "cnt:ContentAsText",
        "chars": "REVANCHE"
      },
      "on": "https://purl.stanford.edu/hn876tb4569/iiif/canvas/http:#xywh=4442,378,1188,112"
    } 
}
```

**Comment by anarchivist** [comment]
sul-dlss/purl#528 is a related issue that also needs to be resolved.

**Comment by anarchivist** [comment]
The pull request has been merged, but the change has not been deployed. The other remaining work will be for Andrew to republish the impacted objects.

**Comment by anarchivist** [comment]
@caaster This change has been deployed, and this object has been reindexed. I'm going to close the issue but please let us know if you see this issue persist.
