### ISSUE TITLE
Pagination analysis

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/content_search#4]
Find worst case search, and see what the performance impact is when returning large results (and what the acceptable threshold for response is).

http://iiif.io/api/search/1.0/#paging-results

**Comment by cbeer** [comment]
Our current response is bounded by solr:

- 10000 pages (way bigger than how many pages a single item has)
- 10 hits per page (possibly not big enough).

We can add pagination through the pages, but no mechanism to add intra-page pagination, so we'll need to make sure the hits per page is large enough to capture them all.

In #13, I've added basic support for pagination (next/first/last properties). Solr doesn't give us a way (that I can figure out) to count the number of highlighting hits (`within/total`) or the offset (`startIndex`), but they are listed as `SHOULD` in the spec.

**Comment by caaster** [comment]
Does this help clarify, @anarchivist ?

A 2-part problem: (1) implementing pagination on our end, technical limitations related to Solr (2) getting UV to support our implementation. No known clients currently support pagination

**Comment by anarchivist** [comment]
Yep, thanks @caaster!
