### ISSUE TITLE
Receive notifications about when OCR content changes

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/content_search#48]
When there is new or changed OCR associated with an object, we should be able to receive notifications that will then lead to the OCR being (re)indexed in the `content_search` index. 

(We think this is PurlFetcher, but there may be work to do.)

**Comment by cbeer** [comment]
If we're doing something PURL-fetcher-esque, the current implementation has: https://github.com/sul-dlss/content_search/blob/master/app/controllers/items_controller.rb
