### ISSUE TITLE
Send notifications when OCR content changes

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/content_search#49]
When OCR content changes on stacks (i.e. is shelved to stacks), the infrastructure should send a notification that the content has changed. This is then received (#48) to to trigger a (re)indexing of that content.

**Comment by anarchivist** [comment]
This ticket may spawn operations tasks depending on what we recommend wrt to implementation.

**Comment by anarchivist** [comment]
Per 2/20 sprint planning, part of this work will be analysis to determine what parts of the infrastructure would need changes.

**Comment by jkeck** [comment]
I believe this is pretty much done, @cbeer would you agree, or should we keep this open to track anything else?

**Comment by cbeer** [comment]
It's not quite done, waiting on https://github.com/sul-dlss/discovery-dispatcher/pull/147.
