### ISSUE TITLE
Terms split across lines have a confusing highlight box

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/content_search#53]
In the following screenshot, I'm searching for the phase `crimes against humanity` within druid `cc842mn9348`. For the last match at the bottom of page 5, the text splits across two lines. The highlight box for match does not include the first word in the phrase.

Recommended resolution when a hit is split across two lines is (in order of highest preference first):

* Implement multi-annotations hits (see [§3.4.4 of the search spec](http://iiif.io/api/search/1.0/#multi-annotations-hits))
* Highlight the entirety of the area that is associated with the match (e.g. extending right to the end of the word boundary for `crimes`, and to the same position on the line below), or
* Highlight the first word in the phrase (e.g. on the first line) and not highlight the rest of matching terms.

Screenshot of current behavior:

![screen shot 2018-01-22 at 11 38 38 pm](https://user-images.githubusercontent.com/73732/35263436-97b2d83a-ffcd-11e7-8617-f7d9d8eba198.png)

**Comment by anarchivist** [comment]
Per sprint planning we will focus on the second option for this ticket; multi-annotations hits should be its own ticket

**Comment by cbeer** [comment]
@anarchivist  can you QA the OCR positioning for the phrase you've highlighted in the screenshot? When I switch it to single-word hits (#62),  I'm seeing the word "Count" preceding it identified as "Crimes".

**Comment by anarchivist** [comment]
Hi @cbeer, this is correct based on the coordinates in the OCR. 

![screen shot 2018-01-29 at 10 05 47 am](https://user-images.githubusercontent.com/73732/35526362-043c0d06-04dc-11e8-828c-f43b7c8a593f.png)
