### ISSUE TITLE
"before" in hits section of response occasionally returns numbers that don't appear in OCR text

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/content_search#54]
In the following screenshot, I'm searching for the phase `crimes against humanity` within druid `cc842mn9348` in Mirador. 

![screen shot 2018-01-22 at 11 46 29 pm](https://user-images.githubusercontent.com/73732/35263675-9ba97b82-ffce-11e7-82ce-26a5d5e7bccf.png)

Looking at the `38,71.34,33.92 humanity:` example (the same as #53), the numbers that appear as the `before` context are not part of the OCR text, but appear to relate to the coordinates of the previous term. This does not happen consistently, either.

**Comment by cbeer** [comment]
Ah, I see what's happening. The highlights we get may include fragments that don't include the starting words, e.g.:

```
00,71.92,40.00 <em>Crimes☞1082.21,757.00,143.84,40.00</em> <em>Against☞1250.01,757.00,167.81,40.00</em> Humanity☞1441.79
```
