### ISSUE TITLE
"before"/"after" returns empty values when search is a phrase wrapped in quotes

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/content_search#55]
When I search for a phrase wrapped in quotes (e.g. `"crimes against humanity"` within druid `cc842mn9348`), the `before` and `after` keys within the `hits` section of the response returns empty strings: 

![screen shot 2018-01-23 at 12 01 48 am](https://user-images.githubusercontent.com/73732/35264186-a4777686-ffd0-11e7-8f31-24046777d52b.png)

I expect to see the context terms before and after and after the matching phrase.

**Comment by anarchivist** [comment]
Per 1/29 sprint planning meeting, the next step is some analysis to determine the feasibility of this.

**Comment by camillevilla** [comment]
After much poking around, the best I've been able to understand is that there is no content in the Solr response for a quote-wrapped search that can be parsed into the `before` and `after` field. 

## Solr response
### with quotes
```json
"ocrtext_en": [
"<em>crimes☞1660.33,1094.11,140.42,33.89 against☞1824.15,1094.11,163.82,33.89 humanity,☞2011.38,1094.11,210.62,33.89</em>",
"<em>crimes☞944.31,1334.89,134.70,32.48 against☞1123.92,1334.89,157.15,32.48 humanity,☞1303.52,1334.89,202.06,32.48</em>",
"<em>crimes☞1977.04,1529.78,134.70,32.48\nagainst☞674.90,1594.74,157.15,32.48 humanity,☞854.51,1594.74,202.06,32.48</em>",
"<em>crimes☞1505.58,1724.67,134.70,32.48 against☞1662.73,1724.67,157.15,32.48 humanity,☞1842.34,1724.67,202.06,32.48</em>",
"<em>crime☞1595.38,1919.56,112.25,32.48 against☞1730.08,1919.56,157.15,32.48 humanity,☞1909.69,1919.56,202.06,32.48</em>"
],
```

### Without quotes
```json
"ocrtext_en": [
"11,46.81,33.89 <em>crimes☞1660.33,1094.11,140.42,33.89</em> <em>against☞1824.15,1094.11,163.82,33.89</em> humanity,☞2011",
"89,44.90,32.48 <em>crimes☞944.31,1334.89,134.70,32.48</em> <em>against☞1123.92,1334.89,157.15,32.48</em> humanity,☞1303",
"78,44.90,32.48 <em>crimes☞1977.04,1529.78,134.70,32.48</em>\n<em>against☞674.90,1594.74,157.15,32.48</em> humanity,☞854.51",
"67,44.90,32.48 <em>crimes☞1505.58,1724.67,134.70,32.48</em> <em>against☞1662.73,1724.67,157.15,32.48</em> humanity,☞1842",
"56,44.90,32.48 <em>crime☞1595.38,1919.56,112.25,32.48</em> <em>against☞1730.08,1919.56,157.15,32.48</em> humanity,☞1909",
"00 the☞1058.94,573.00,65.32,33.00 <em>crimes☞1146.04,573.00,130.65,33.00</em> to☞1298.46,573.00,43.55,33.00 which☞1363"
],
```

## highlighting

Question: Why do we only get two highlights when searching without quotes? 


### without quotes
![sample_search_without_quotes](https://user-images.githubusercontent.com/5402927/35887008-c879e19a-0b47-11e8-88c9-b3e0dad7b376.png)

### with quotes
search: "crimes against humanity"
![sample_search_with_quotes](https://user-images.githubusercontent.com/5402927/35886952-a083abee-0b47-11e8-8e69-548856df83ef.png)

**Comment by anarchivist** [comment]
I talked with @camillevilla about this briefly, but we may want to look at the [Unified Highlighter](https://lucene.apache.org/solr/guide/6_6/highlighting.html#Highlighting-TheUnifiedHighlighter), which is new as of Solr 6.4. 

I'm not sure the overall impact of switching to the Unified Highlighter yet, and we'll need to do some tweaking to identify the breakiterator properly. With `hl.method=unified&hl.bs.type=WHOLE` as part of the query, I see examples like the following for the query `ocrtext_en:"crimes against humanity"`:

```
 "ocrtext_en": [
        "Count☞660.76,1871.00,93.82,63.00 1.☞773.35,1871.00,37.53,63.00 <em>Crimes☞829.64,1871.00,112.58,63.00</em> <em>Against☞960.99,1871.00,131.35,63.00</em> <em>Humanity:☞1111.10,1871.00,168.88,63.00</em> Persecution☞1298.74,1871.00,206.40,63.00 (Destruction☞1523.90,1871.00,225.17,63.00 of☞1767.83,1871.00,37.53,63.00 Property)☞1824.12,1871.00,168.88,63.00",
        "Count☞659.00,1932.00,97.45,53.00 2.☞775.94,1932.00,38.98,53.00 <em>Crimes☞834.40,1932.00,116.94,53.00</em> <em>Against☞970.83,1932.00,136.43,53.00</em> <em>Humanity:☞1126.74,1932.00,175.40,53.00</em> Inhumane☞1321.64,1932.00,155.91,53.00 Acts☞1497.04,1932.00,77.96,53.00",
        "Count☞667.00,1993.00,99.75,49.00 3.☞786.70,1993.00,39.90,49.00 <em>Crimes☞846.55,1993.00,119.70,49.00</em> <em>Against☞986.20,1993.00,139.65,49.00</em> <em>Humanity:☞1145.80,1993.00,179.55,49.00</em> Murder☞1345.30,1993.00,119.70,49.00",
        "Count☞661.00,2109.00,100.25,55.00 4.☞781.30,2109.00,40.10,55.00 <em>Crimes☞841.45,2109.00,120.30,55.00</em> <em>Against☞981.80,2109.00,140.35,55.00</em> <em>Humanity:☞1142.20,2109.00,180.45,55.00</em> Murder☞1342.70,2109.00,120.30,55.00",
        "Count☞665.00,2173.00,96.27,59.00 5.☞780.52,2173.00,38.51,59.00 <em>Crimes☞838.28,2173.00,115.52,59.00</em> <em>Against☞973.06,2173.00,134.78,59.00</em> <em>Humanity:☞1127.09,2173.00,173.28,59.00</em> Enforced☞1319.63,2173.00,154.03,59.00 disappearance☞1492.91,2173.00,250.30,59.00 of☞1762.46,2173.00,38.51,59.00 persons☞1820.22,2173.00,134.78,59.00",
        "Count☞667.00,2238.00,92.35,57.00 5.☞777.82,2238.00,36.94,57.00 (altern)☞833.23,2238.00,147.76,57.00 <em>Crimes☞999.45,2238.00,110.82,57.00</em> <em>Against☞1128.74,2238.00,129.29,57.00</em> <em>Humanity:☞1276.50,2238.00,166.23,57.00</em> Persecution☞1461.20,2238.00,203.17,57.00 (Abduction)☞1682.83,2238.00,203.17,57.00",
        "Count☞659.00,2432.00,93.26,60.00 6.☞770.92,2432.00,37.31,60.00 <em>Crimes☞826.88,2432.00,111.92,60.00</em> <em>Against☞957.44,2432.00,130.57,60.00</em> <em>Humanity:☞1106.67,2432.00,167.88,60.00</em> Persecution☞1293.19,2432.00,205.18,60.00 (Destruction☞1517.03,2432.00,223.83,60.00 of☞1759.51,2432.00,37.31,60.00 Property).☞1815.47,2432.00,186.53,60.00",
        "Count☞661.00,2494.00,98.62,61.00 7.☞779.34,2494.00,39.45,61.00 <em>Crimes☞838.51,2494.00,118.34,61.00</em> <em>Against☞976.57,2494.00,138.06,61.00</em> <em>Humanity:☞1134.36,2494.00,177.51,61.00</em> Inhumane☞1331.60,2494.00,157.79,61.00 Acts☞1509.11,2494.00,78.89,61.00",
        "Count☞664.00,2623.00,98.09,54.00 8.☞781.70,2623.00,39.23,54.00 <em>Crimes☞840.55,2623.00,117.70,54.00</em> <em>Against☞977.87,2623.00,137.32,54.00</em> <em>Humanity:☞1134.81,2623.00,176.55,54.00</em> Inhumane☞1330.98,2623.00,156.94,54.00 Acts☞1507.53,2623.00,78.47,54.00",
        "Count☞661.00,2748.00,90.52,57.00 <em>9.Crimes☞769.62,2748.00,144.83,57.00</em> <em>Against☞932.55,2748.00,126.72,57.00</em> <em>Humanity:☞1077.38,2748.00,162.93,57.00</em> deportation☞1258.41,2748.00,199.14,57.00 or☞1475.66,2748.00,36.21,57.00 forcible☞1529.97,2748.00,144.83,57.00 transfer☞1692.90,2748.00,144.83,57.00 of☞1855.83,2748.00,36.21,57.00 population....☞1910.14,2748.00,253.45,57.00 19☞2199.79,2748.00,36.21,57.00"
      ],
```

**Comment by camillevilla** [comment]
2/20: This is moving to the backlog for now. We'll want to revisit this ticket (analysis, update parsing) after making a decision about how / whether we'll use the Unified Highlighter (#67)

**Comment by anarchivist** [comment]
Status as of 4/3: is this solved by Unified Highlighter? Figure out next steps

**Comment by anarchivist** [comment]
Here's what I'm seeing with what's running on `sul-contentsearch-uat`:

<img width="1059" alt="screen shot 2018-04-04 at 1 36 43 pm" src="https://user-images.githubusercontent.com/73732/38333370-48216e8a-380d-11e8-9701-f5a7963d2040.png">

It appears that phrase queries are matching each of the terms within the phrase more than once. Is there something that we can do to address this to ensure only one match in such cases?

**Comment by anarchivist** [comment]
To do: Review level of effort to potentially fix this, using at most ~8 hours of dev time. We should then get an estimate for me to assess the complexity of implementing this correctly in the current work cycle. Search UX designs for UV include `before`/`after` but we don't know if they'll be in scope yet for the remaining UV contract time.
