### ISSUE TITLE
What is autocomplete matching on?

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/content_search#56]
Looking at a few example autocomplete lookups, I'm noticing that phrases are returned:

![screen shot 2018-01-23 at 12 20 27 am](https://user-images.githubusercontent.com/73732/35265226-5f260526-ffd4-11e7-9d28-36d56e2f10c4.png)

![screen shot 2018-01-23 at 12 18 03 am](https://user-images.githubusercontent.com/73732/35265227-5f42ab2c-ffd4-11e7-89d8-43003c8aa798.png)

What determines the terms/phrases that end up being included in the autocomplete index?

**Comment by cbeer** [comment]
It's pretty naive right now -- it's just 1-5 word chunks, and returning relevant selections using lucene's normal matching. There's also some other logic carried over from the suggester we based work on for matching 1-3 character queries, so the results may change after that.

As we're writing our own suggester (and have full control over how analysis happens), you and Gary might as well specify some design criteria and we can see what's possible.

**Comment by anarchivist** [comment]
Per conversation on the 23 Jan sprint planning call, we should spend some time thinking about the design implications for this, so I've added it to `design needed` for @ggeisler to pick up.

**Comment by anarchivist** [comment]
Work on these issues continues under #63 and #64.
