### ISSUE TITLE
Autocomplete queries - handle words and phrases differently

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/content_search#64]
Spun out of #56 and discussed w/ @jvine and @ggeisler on 1/31. Edited 2/7 to include @jvine's comment.

* [x] By default, autocomplete queries should only match single words unless a user enters a space.
* If a user enters a space after a query term in an autocomplete query:
    * [x] ... the response should return the phrases that start with the query term and the next matching set of terms
    * [x] ... and enters more characters for a term, that should be expanded to show matching terms until the next space
    * [x] ... and another term and space occurs, the behavior should repeat.
* [ ] If a user selects an autocomplete query response item that is a phrase, that search should then lead to results for a phrase query.

For example:

* if I type in `egg`, I should see `egg`, `egghead`, `eggs`, etc.
* From if there, if I enter a space (`egg␠`), I should see `egg␠about`, `egg␠any`, `egg␠apple` ... 
* From there, if I continue typing `egg␠bea`, I should see `egg␠bead`, `egg␠beard`, `egg␠beast`, etc.
* From there, if I I continue typing `egg␠beast␠`, I should see `egg␠beast␠about` ... 
* From there, if I continue typing `egg␠beast␠mod`, I should see `egg␠beast␠mode`, `egg␠beast␠models`.
* Selecting `egg␠beast␠mode` should lead to query results for the phrase `egg␠beast␠mode`.

**Comment by jvine** [comment]
I wonder if `egg[space]` could start adding the second terms, without the user having to type three letters of the following word. That is, expose to the user sooner that multiple term typeahead is possible, and continue to respond one letter at a time. 

`egg[space]` would give `egg about`, `egg any`, `egg apple`, etc.
`egg b` would give `egg batter`, `egg bead`, etc.
`egg be` gives `egg bead`, `egg beard`, `egg beast`
`egg beast[space]` gives `egg beast about`... and so on forever.

**Comment by anarchivist** [comment]
@jvine I like this suggestion.

**Comment by cbeer** [comment]
I think https://github.com/sul-dlss/content_search/pull/51 is related to the third point.

**Comment by mejackreed** [comment]
## Initial analysis

In my initial research into this ticket, I think we have some easy win opportunities to solve a lot of this. Right now our suggester is returning 5 results, and these are not sorted in any useful way, they essentially are returned based on their location in the document.

Example:

Search [`con`](http://127.0.0.1:8983/solr/content_search/suggest?suggest.count=4&suggest.q=con):

```json
{
   "responseHeader":{
      "status":0,
      "QTime":1
   },
   "suggest":{
      "mySuggester":{
         "con":{
            "numFound":4,
            "suggestions":[
               {
                  "term":"<b>con</b>cluded",
                  "weight":2,
                  "payload":""
               },
               {
                  "term":"<b>con</b>cluded today",
                  "weight":1,
                  "payload":""
               },
               {
                  "term":"<b>con</b>cluded today the 7",
                  "weight":1,
                  "payload":""
               },
               {
                  "term":"<b>con</b>cluded today the",
                  "weight":1,
                  "payload":""
               }
            ]
         }
      }
   }
}
```

These results appear all on the first canvas with text on them in order. 

But a [much longer results list](http://127.0.0.1:8983/solr/content_search/suggest?suggest.count=400&suggest.q=con) (400) produced better suggestions that have higher weights. So not only is "concluded" suggested, but also convicted, conducted, etc. are also return. This may be a bit outside the actionable items in this ticket, but I think providing a sorted weight response would give us much better results.

## Approaches to consider

### Just do it in Ruby
This approach could work in some scenarios. It would require us to return a sufficiently large count from Solr and then sort the results and only provide back the top `n`. This would likely have significant performance impacts and doesn't feel like a decent solution for us.

### Fix it in our Solr suggester
Discussed with @cbeer on 2/22. Seems like a good stable long term approach but will require a bit of understanding how Solr groupings and sorts work.

Relevant links:
Potential place for a fix: https://github.com/apache/lucene-solr/compare/master...cbeer:tokenizing-suggester-upstreamable?expand=1#diff-646f2aefb1b14b52becbdd0c65eb1005R685
The suggester @cbeer built this off of https://github.com/apache/lucene-solr/blob/812711416d903be47a2bf14c64aabf67e0753a5d/lucene/suggest/src/java/org/apache/lucene/search/suggest/analyzing/AnalyzingInfixSuggester.java

**Comment by jkeck** [comment]
Agree that doing it in ruby does not seem like a good solution.

**Comment by mejackreed** [comment]
A modified suggester pushed up here: https://github.com/sul-dlss/content_search/tree/modified-sorting-suggester

Though the suggester still has some issues as it can't return a global weight documents.

**Comment by mejackreed** [comment]
It also appears that UV stops querying a search service autocomplete after a space is entered.

**Comment by tomcrane** [comment]
I suspect the reason for not searching on space is down to the original Wellcome implementation (pre-IIIF, I would have guessed that line was earlier than 2015). In that implementation, the source of autocomplete words is a simple set of all the distinct words in the text (which is still pretty useful). Anything with a space in it couldn't match any results. The solution seems pretty clear - make it a config option whether to carry out an autocomplete query when there's a space in the q param. If the back end is capable of more sophisticated completion, you enable it.

**Comment by mejackreed** [comment]
@anarchivist the changes inspired by this ticket are now deployed out to uat. I think we this can either:

 - be closed and autocomplete re-evaluated?
 - moved to the backlog or design for additional review?

**Comment by anarchivist** [comment]
Assigning myself to review and moving to needs review. I probably won't get to it until late this week, but it's on my todo list.

**Comment by anarchivist** [comment]
Audit whether the acceptance criteria are still valid, and determine whether changes introduced are sufficient

**Comment by anarchivist** [comment]
Notes from my convo with @mejackreed on 3/23:

- Current implementation is a slightly different approach
- Change 1: includes UniversalViewer/universalviewer#552 - multiword phrases
- Change 2: based on analysis of sorting for autocomplete. previously they were returned by order of appearance. This is #77 - return autocomplete results sorting changed. The assumption is that frequency is a valid way to sort the autocomplete results.
- This does not sort in alpha order, which the ticket suggests. Sorting behavior can be changes as needed

**Comment by anarchivist** [comment]
Apologies for the delay in my review. I think this looks great, and the alphabetical order was not an explicit part of the acceptance criteria. I think the only thing that wasn't addressed is the phrase query behavior, which I think is fine after testing. Thanks!
