### ISSUE TITLE
Add multilingual support

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/content_search#9]
Hopefully this is just indexing support, but we should validate against our responses.

**Comment by anarchivist** [comment]
Based on conversation on 12/14/17, we know that the stakeholders at least have an interest in stemming. Currently, we only know which languages the entire document is in.

* [ ] Language-specific fields for indexing (English, Portuguese, and Indonesian)
* [ ] Determine whether it's an issue whether we index a document as Portuguese if it's 90% English
* [ ] Confirm that diacritics work as expected - (e.g. If I search for `Gonçalves`, I should find `Gonçalves`; if I search for `Goncalves` I should find `Gonçalves` and `Goncalves`)
